version: '3'
services:
  my-postgres:
    image: postgres
    ports:
      - "8888:5432"
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - ./dbscript.sql:/docker-entrypoint-initdb.d/create_tables.sql
  spring-backend-service:
    image: docker-spring-boot-postgres
    build: .
    depends_on:
      - my-postgres
    
